package es.pildoras.IoC;

public class SecretaryEmployee implements Employees {

	private CreationReports newReport;
	private String email;
	private String companyName;

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getCompanyName() {
		return companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	public void setNewReport(CreationReports newReport) {
		this.newReport = newReport;
	}

	@Override
	public String getTasks() {
		// TODO Auto-generated method stub
		return "Manage the schedule of bosses";
	}

	@Override
	public String getReport() {
		// TODO Auto-generated method stub
		return "Report generated by the secretary: " + newReport.getReport();
	}

}
