package es.pildoras.testannotations;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

@Component
public class ExperiencedCommercial implements Employees {

	@Autowired
	private CreationFinancialReport newReport;

	public ExperiencedCommercial() {
	}

	/*
	 * @Autowired public ExperiencedCommercial(CreationFinancialReport newReport) {
	 * this.newReport = newReport; }
	 */

	/*
	 * @Autowired public void anyName(CreationFinancialReport newReport) {
	 * this.newReport = newReport; }
	 */

	@Override
	public String getTasks() {
		// TODO Auto-generated method stub
		return "Sell, sell and sell more!";
	}

	@Override
	public String getReport() {
		// TODO Auto-generated method stub
//		return "Report generated by the commercial";
		return newReport.getFinancialReport();
	}

}
