package es.pildoras.testannotations;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Component;

@Component
public class ExperiencedCommercial implements Employees {

	@Autowired
	@Qualifier("financialReportQuart4") // bean Id that it must use
	private CreationFinancialReport newReport;

	public ExperiencedCommercial() {
	}

	/*
	 * @Autowired public ExperiencedCommercial(CreationFinancialReport newReport) {
	 * this.newReport = newReport; }
	 */

	/*
	 * @Autowired public void anyName(CreationFinancialReport newReport) {
	 * this.newReport = newReport; }
	 */

	@Override
	public String getTasks() {
		// TODO Auto-generated method stub
		return "Sell, sell and sell more!";
	}

	@Override
	public String getReport() {
		// TODO Auto-generated method stub
//		return "Report generated by the commercial";
		return newReport.getFinancialReport();
	}

	// code execution after Bean creation
//	@PostConstruct
	public void executeAfterCreation() {
		System.out.println("Executed after bean creation");
	}

	// code execution before Spring container shutdown
//	@PreDestroy
	public void executeBeforeDestruction() {
		System.out.println("Executed before destruction");
	}

}
